### PR TITLE
Build conda packages for Python 3.8 - 3.11

### LINKED ISSUE #29: Custom conda XSD packages
**Description**
PyChaste relies on the [XSD package from the bioconda channel](https://anaconda.org/bioconda/xsd/files) which is only available for Linux.

Creating custom XSD packages on the [PyChaste channel](https://anaconda.org/PyChaste/) would
* Reduce the number of channels needed for retrieving PyChaste dependencies.
* Help enable Mac support for PyChaste (#17).

### LINKED ISSUE #42: Build conda packages for Python 3.8 - 3.12
**Description**
The conda package is currently only available for Python 3.10. To allow installation in a wider variety of environments, more packages should be built for other Python versions.

This will also require building a custom VTK7 package for multiple Python versions.

### LINKED ISSUE #62: Release PyChaste 2024.1
**Summary**

* Update PyChaste wrappers for Chaste release 2024.1.

TODO
- [x] Fix broken wrappers
- [x] Create new wrappers for Immersed Boundary code.
- [x] Create PyChaste Immersed Boundary tutorial.
- [x] Visualise outputs from Immersed Boundary tutorial.
- [x] Build conda packages for Python 3.8 to 3.11
- [x] Release PyChaste 2024.1

### PR DESCRIPTION
**Pull request by kwabenantim**
**Summary**
* Supports #42 
* Supports #28

### CODE REVIEW

**Comment by kwabenantim** [comment]
**Failure to resolve conda build dependencies**
The minimum version of [petsc4py](https://anaconda.org/conda-forge/petsc4py) on conda-forge that supports Python 3.11 is `petsc4py 3.17.4` which depends on:
```
libgcc-ng >=12, libgfortran-ng, libgfortran5 >=10.4.0, mpich >=4.0.2,<5.0a0, numpy >=1.21.6,<2.0a0, 
petsc >=3.17.4,<3.18.0a0 real_*, python >=3.10,<3.11.0a0, python >=3.10,<3.11.0a0 *_cpython, python_abi 3.10.* *_cp310
```

In turn, [petsc 3.17.4](https://anaconda.org/conda-forge/petsc) from conda-forge depends on:
```
fftw * mpi_openmpi_*, hdf5 * mpi_openmpi_*, hdf5 >=1.12.2,<1.12.3.0a0 mpi_openmpi_*, 
hypre >=2.25.0,<2.25.1.0a0, libblas >=3.9.0,<4.0a0, libcblas >=3.9.0,<4.0a0, libgcc-ng >=12, 
libgfortran-ng, libgfortran5 >=10.4.0, liblapack >=3.9.0,<4.0a0, libstdcxx-ng >=12, 
metis >=5.1.0,<5.2.0a0, mumps-mpi >=5.2.1,<5.2.2.0a0, openmpi >=4.1.4,<5.0a0, 
parmetis >=4.0.3,<4.1.0a0, ptscotch >=6.0.9,<6.0.10.0a0, scalapack >=2.2.0,<2.3.0a0, 
scotch >=6.0.9,<6.0.10.0a0, suitesparse >=5.10.1,<5.11.0a0, superlu, superlu_dist >=7.1.1,<8.0a0, 
yaml >=0.2.5,<0.3.0a0
```
However, Chaste does not yet support `hdf5 1.12`.

**Comment by bdevans** [comment]
Ok, good investigating! Maybe time to open an issue in the main repo to add support for `hdf5>=1.12` then?

**Comment by kwabenantim** [comment]
The investigation for supporting HDF 1.12 had already started on an old trac ticket (now a github issue):
* https://github.com/Chaste/Chaste/issues/163

**Comment by kwabenantim** [comment]
We now have vtk 7.1.1 built for Python 3.11 (https://anaconda.org/PyChaste/vtk/files).
Next step is to build PyChaste for Python 3.11.

**Comment by kwabenantim** [comment]
The VTK conda build has some fixed paths in its generated CMake configuration that need fixing.

```
make[3]: *** No rule to make target 
'/home/conda/feedstock_root/build_artifacts/vtk_1696254766018/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/libSM.so', 
needed by 'projects/PyChaste/libchaste_project_PyChaste.so'.  Stop.
```

**Comment by kwabenantim** [comment]
### Fixes

**VTKConfig.cmake**
```diff
-if (VTK_USE_CXX11_FEATURES)
-  if (CMAKE_VERSION VERSION_LESS "3.1")
-    message(FATAL_ERROR "VTK was built with C++11 features using CMake's CXX_STANDARD_REQUIRED feature.  Configuring projects this way requires a newer version of CMake.  Please update to CMake 3.1 or newer")
-  endif()
-  set(CMAKE_CXX_STANDARD 11)
-  set(CMAKE_CXX_STANDARD_REQUIRED 11)
-endif()
```


**VTKTargets.cmake**
Remove `/home/conda/feedstock_root/build_artifacts/vtk_1696254766018/_build_env/x86_64-conda-linux-gnu/sysroot/usr/lib/` from all paths passed to the linker.

**Comment by kwabenantim** [comment]
Need to update build scripts to narrow down dependencies due to installation issues:
* https://github.com/Chaste/PyChaste/issues/55

**Comment by kwabenantim** [comment]
**Conda Builds for PyChaste and VTK**
- [x] Python 3.8
- [x] Python 3.9
- [x] Python 3.10
- [x] Python 3.11
- [x] Python 3.12 (skipped)

**Comment by kwabenantim** [comment]
[Colab Notebook](https://colab.research.google.com/drive/1owrQnJkQDBFpv62GcGpoJrq9Uhh0VPxa?usp=sharing) for Immersed Boundary tutorial working okay.

**Comment by kwabenantim** [comment]
Skipping Python 3.12 as vtk 7 python wrapping contains deprecated functionality. Support for newer vtk versions should fix this in #23 and #24

**Pull request merged**
