### PR TITLE
Update PyChaste Docker Image

### LINKED ISSUE #28: Update PyChaste docker image
**Description**
The PyChaste [docker image](https://hub.docker.com/r/jmsgrogan/pychaste) was last updated in 2016.

**To Do**
- [x] Update the docker image to the latest version of Chaste/develop (or the next Chaste release if ready).
- [x] Move the docker image to the [Chaste dockerhub repository](https://hub.docker.com/u/chaste).

### PR DESCRIPTION
**Pull request by kwabenantim**
**Summary**
Create an updated docker image for PyChaste.

**Related Issues**
* #28

### CODE REVIEW

**Comment by kwabenantim** [comment]
Building the image seems to have dependency resolution issues although pychaste conda packages have been built for Python 3.11 here: https://anaconda.org/PyChaste/repo.

```
Pinned packages:
  - python 3.11.*
  - python 3.11.6
  - jupyterlab >=4.0.4
  - notebook >=7.0.2
  
...
│  │  │  ├─ vtk 7.1.1 would require
│  │  │  │  ├─ jpeg >=9e,<10a , which can be installed;
│  │  │  │  ├─ libtiff >=4.5.0,<4.6.0a0  with the potential options
│  │  │  │  │  ├─ libtiff [4.4.0|4.5.0] would require
│  │  │  │  │  │  └─ libdeflate >=1.14,<1.15.0a0 , which can be installed;
│  │  │  │  │  ├─ libtiff 4.5.0 would require
│  │  │  │  │  │  └─ libdeflate >=1.17,<1.18.0a0 , which can be installed;
│  │  │  │  │  ├─ libtiff 4.5.0 would require
│  │  │  │  │  │  └─ libdeflate >=1.16,<1.17.0a0 , which can be installed;
│  │  │  │  │  └─ libtiff [4.5.0|4.5.1] would require
│  │  │  │  │     └─ libdeflate >=1.18,<1.19.0a0 , which conflicts with any installable versions previously reported;
│  │  │  │  └─ libxml2 >=2.10.3,<2.11.0a0  but there are no viable options
│  │  │  │     ├─ libxml2 2.10.3 would require
│  │  │  │     │  └─ icu >=70.1,<71.0a0 , which conflicts with any installable versions previously reported;
│  │  │  │     └─ libxml2 [2.10.3|2.10.4] would require
│  │  │  │        └─ icu >=72.1,<73.0a0 , which conflicts with any installable versions previously reported;
...
 ```

**Comment by kwabenantim** [comment]
> Building the image seems to have dependency resolution issues although pychaste conda packages have been built for Python 3.11 here: https://anaconda.org/PyChaste/repo.

Switched to micromamba image to start from a blank environment [804c3372](https://github.com/Chaste/PyChaste/pull/52/commits/804c33721bfd53ae4363992c896528dfa7a603c7).

**Comment by kwabenantim** [comment]
The new image seems to be working now. Currently testing:
`docker run --init -it --rm -p 8888:8888 kwabenantim/pychaste`

**Review by mirams — APPROVED** [review]
Haven't tried it out, but all changes look sensible!

**Comment by bdevans** [comment]
Slightly late to the party but it looks good! The main change I would consider is using the newer `jupyterlab` package rather than `notebook` (unless that was what caused the dependency issues above).

**Comment by kwabenantim** [comment]
> Slightly late to the party but it looks good! The main change I would consider is using the newer `jupyterlab` package rather than `notebook` (unless that was what caused the dependency issues above).

Thanks @bdevans. I'll make the changes in a new PR.

**Comment by bdevans** [comment]
Oh, some labels are also a good idea. e.g. you could adapt these ones from the base image:
```
LABEL maintainer="Ben Evans <ben.d.evans@gmail.com>" \
    author.orcid="https://orcid.org/0000-0002-1734-6070" \
    image.publication="https://doi.org/10.21105/joss.01848" \
    org.opencontainers.image.authors="Benjamin D. Evans" \
    org.opencontainers.image.url="https://github.com/Chaste/chaste-docker" \
    org.opencontainers.image.licenses="MIT" \
    org.opencontainers.image.title="Chaste Docker Image" \
    org.opencontainers.image.description="Chaste: Cancer, Heart and Soft Tissue Environment" \
    org.opencontainers.image.documentation="https://chaste.github.io/docs/installguides/docker/"
```

**Pull request merged**
