### PR TITLE
Fix Jekyll Site

### LINKED ISSUE #34: Move PyChaste website
**Description**
Move the [PyChaste website](https://jmsgrogan.github.io/PyChaste/) to the Chaste organisation under [chaste.github.io](https://chaste.github.io)

**Related PRs**
* https://github.com/Chaste/Chaste.github.io/pull/17

**To Do**
- [x] Add PyChaste markdown pages to site (https://github.com/Chaste/Chaste.github.io/pull/17)
- [x] Automatically generate tutorial markdown (https://github.com/Chaste/PyChaste/pull/50)
- [x] Add landing page for PyChaste (https://github.com/Chaste/Chaste.github.io/issues/22)
- [x] Fix tutorial syntax highlighting (https://github.com/Chaste/Chaste.github.io/issues/22)
- [ ] Move PyChaste Python API docs (https://github.com/Chaste/Chaste.github.io/issues/22)
- [ ] Update PyChaste pages for trunk merge: https://github.com/Chaste/Chaste.github.io/pull/101
- [ ] Add PyChaste Dev Guide #47

### PR DESCRIPTION
**Pull request by kwabenantim**
**Summary**
* Supports #34

### CODE REVIEW

**Comment by kwabenantim** [comment]
The site can now be viewed at https://chaste.github.io/PyChaste/

**Review by fcooper8472 — COMMENTED** [review]
@kwabenantim is it right that there's a load of HTML in here? Rather than a load of pages that get rendered to HTML at build time?

Or is the gh-pages branch the built site?

**Comment by kwabenantim** [comment]
@fcooper8472 it looks like the pages were written in html. There don't seem to be any markdown files except for a few readmes:
```
README.md
blog/README.md
events/README.md
news/README.md
training/README.md
```

Initial site: [577c2f6a](https://github.com/Chaste/PyChaste/commit/577c2f6a7b088e351fb3ec1a1abdcb82d435490a)

**Comment by kwabenantim** [comment]
@fcooper8472, might be an idea to recreate it in markup on the main chaste.github.io?

**Comment by mirams** [comment]
If I read it right, that original committed blurb says it is HTML autogenerated by Jekyll, in which case it is probably all in markdown somewhere originally?

**Comment by kwabenantim** [comment]
> If I read it right, that original committed blurb says it is HTML autogenerated by Jekyll, in which case it is probably all in markdown somewhere originally?

Thanks @mirams. I've found the markdown on [PyChaste.web](https://github.com/jmsgrogan/PyChaste.web/tree/master). There seems to be quite a bit of scala-specific content in there that we probably don't want to keep. I'll slim it down and either move it to the `gh-pages` branch or directly to the [chaste.github.io](https://chaste.github.io) Hugo site.

**Comment by kwabenantim** [comment]
This approach is to be abandoned. The PyChaste website will be re-created in markdown directly under chaste.github.io

**Pull request closed without merging**
